# Generated by Django 3.1.6 on 2021-02-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='title',
            field=models.CharField(default='Software Engineer', max_length=80),
        ),
    ]
