# Generated by Django 3.1.6 on 2021-02-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_applications_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
