# Generated by Django 3.1.6 on 2021-02-10 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210210_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('interviewer', models.CharField(max_length=50)),
                ('notes', models.TextField(max_length=250)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.applications')),
            ],
        ),
    ]
